import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useMemo, useState } from "react";
import { FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { findCzechRhymes } from "@/lib/czech-rhymes";
import { useColors } from "@/hooks/use-colors";

export function RhymeFinder({ onInsert }: { onInsert: (word: string) => void }) {
  const colors = useColors();
  const [visible, setVisible] = useState(false);
  const [query, setQuery] = useState("");
  const suggestions = useMemo(() => findCzechRhymes(query), [query]);
  const choose = (word: string) => { onInsert(word); setVisible(false); };
  return <><Pressable onPress={() => setVisible(true)} style={({ pressed }) => [styles.trigger, { borderColor: colors.border, backgroundColor: `${colors.primary}12`, opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="auto-awesome" size={19} color={colors.primary} /><View style={styles.triggerCopy}><Text style={[styles.triggerTitle, { color: colors.foreground }]}>Hledač rýmů</Text><Text style={[styles.triggerText, { color: colors.muted }]}>Najdi rým a vlož jej do konce textu.</Text></View><MaterialIcons name="chevron-right" size={22} color={colors.primary} /></Pressable>
    <Modal visible={visible} transparent animationType="slide" onRequestClose={() => setVisible(false)}><View style={styles.shade}><View style={[styles.sheet, { backgroundColor: colors.background }]}><View style={[styles.handle, { backgroundColor: colors.border }]} /><View style={styles.top}><View><Text style={[styles.title, { color: colors.foreground }]}>Hledač českých rýmů</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Zadej slovo a vyber návrh pro vložení.</Text></View><Pressable onPress={() => setVisible(false)} style={({ pressed }) => [styles.close, { backgroundColor: colors.surface, opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="close" size={20} color={colors.foreground} /></Pressable></View><TextInput value={query} onChangeText={setQuery} autoFocus placeholder="Např. noc, láska, svět…" placeholderTextColor={colors.muted} autoCapitalize="none" style={[styles.input, { color: colors.foreground, backgroundColor: colors.surface, borderColor: colors.border }]} />
      {query.trim().length < 2 ? <View style={styles.empty}><MaterialIcons name="search" size={28} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Napiš hledané slovo</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Návrhy porovnávají české koncovky slov a zobrazí přesné i volnější rýmy.</Text></View> : <FlatList data={suggestions} keyExtractor={(item) => item.word} contentContainerStyle={styles.results} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="sentiment-dissatisfied" size={28} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.foreground }]}>Rým zatím nemám</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Zkus kratší tvar slova nebo jiný pád.</Text></View>} renderItem={({ item }) => <Pressable onPress={() => choose(item.word)} style={({ pressed }) => [styles.result, { backgroundColor: colors.surface, borderColor: colors.border, opacity: pressed ? 0.68 : 1 }]}><View><Text style={[styles.word, { color: colors.foreground }]}>{item.word}</Text><Text style={[styles.label, { color: item.label === "Přesný rým" ? colors.success : colors.muted }]}>{item.label}</Text></View><MaterialIcons name="add-circle-outline" size={21} color={colors.primary} /></Pressable>} />}
    </View></View></Modal></>;
}

const styles = StyleSheet.create({ trigger: { minHeight: 62, borderWidth: 1, borderRadius: 17, padding: 12, flexDirection: "row", alignItems: "center", gap: 10 }, triggerCopy: { flex: 1, gap: 2 }, triggerTitle: { fontSize: 14, fontWeight: "900" }, triggerText: { fontSize: 11, lineHeight: 15 }, shade: { flex: 1, backgroundColor: "rgba(0,0,0,0.48)", justifyContent: "flex-end" }, sheet: { maxHeight: "84%", borderTopLeftRadius: 27, borderTopRightRadius: 27, paddingHorizontal: 20, paddingBottom: 26 }, handle: { width: 42, height: 4, borderRadius: 3, alignSelf: "center", marginVertical: 10 }, top: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 14 }, title: { fontSize: 18, fontWeight: "900" }, subtitle: { fontSize: 12, marginTop: 3 }, close: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center" }, input: { minHeight: 49, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, fontSize: 16, marginBottom: 13 }, results: { gap: 8, paddingBottom: 10 }, result: { minHeight: 58, borderWidth: 1, borderRadius: 15, paddingHorizontal: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, word: { fontSize: 16, fontWeight: "900" }, label: { fontSize: 11, fontWeight: "700", marginTop: 2 }, empty: { paddingVertical: 34, paddingHorizontal: 18, alignItems: "center", gap: 7 }, emptyTitle: { fontSize: 14, fontWeight: "900" }, emptyText: { textAlign: "center", fontSize: 12, lineHeight: 17 } });
