import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { EmptyState, LoadingState, SectionTitle, StudioHeader } from "@/components/studio-ui";
import { ScreenContainer } from "@/components/screen-container";
import { startOAuthLogin } from "@/constants/oauth";
import { useAuth } from "@/hooks/use-auth";
import { useColors } from "@/hooks/use-colors";
import { downloadOrShareFile } from "@/lib/download-and-share";
import { trpc } from "@/lib/trpc";

export default function SettingsScreen() {
  const colors = useColors();
  const { user, isAuthenticated, loading, logout } = useAuth();
  const snapshot = trpc.studio.snapshot.useQuery(undefined, { enabled: isAuthenticated });
  const authLogout = trpc.auth.logout.useMutation();
  const exportWholeLibrary = trpc.studio.exportWholeLibrary.useMutation();
  if (loading || (isAuthenticated && snapshot.isLoading)) return <ScreenContainer><LoadingState /></ScreenContainer>;
  if (!isAuthenticated) return <ScreenContainer className="p-5 justify-center"><EmptyState icon="lock" title="Připoj své studio" text="Přihlášení vytváří soukromé úložiště pro tvé texty, přebaly a MP3." action={<Pressable onPress={() => void startOAuthLogin()} style={[styles.login, { backgroundColor: colors.primary }]}><Text style={styles.loginText}>Přihlásit se</Text></Pressable>} /></ScreenContainer>;
  const versions = snapshot.data?.versions.length ?? 0;
  const showLogout = () => Alert.alert("Odhlásit SongCraft Studio?", "Lokální obrazovka se odhlásí, data zůstanou bezpečně v cloudu.", [{ text: "Zrušit", style: "cancel" }, { text: "Odhlásit", style: "destructive", onPress: async () => { await authLogout.mutateAsync(); await logout(); } }]);
  const exportLibrary = async () => { try { const archive = await exportWholeLibrary.mutateAsync(); await downloadOrShareFile(archive.url, archive.fileName, "application/zip", "Uložit kompletní archiv SongCraft Studio"); Alert.alert("Kompletní export je připraven", "Archiv obsahuje texty, prompty, alba, obrázky, MP3 a metadata."); } catch (error) { Alert.alert("Export celé knihovny se nezdařil", error instanceof Error ? error.message : "Zkus to znovu."); } };
  return <ScreenContainer className="px-5"><ScrollView contentContainerStyle={styles.content}><StudioHeader eyebrow="Osobní pracovní prostor" title="Nastavení" /><View style={[styles.profile, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: `${colors.primary}26` }]}><Text style={[styles.avatarText, { color: colors.primary }]}>{(user?.name ?? "S").slice(0, 1).toUpperCase()}</Text></View><View style={styles.profileCopy}><Text style={[styles.profileName, { color: colors.foreground }]}>{user?.name ?? "SongCraft autor"}</Text><Text numberOfLines={1} style={[styles.profileMail, { color: colors.muted }]}>{user?.email ?? "Soukromý cloudový účet"}</Text></View><MaterialIcons name="verified-user" size={22} color={colors.success} /></View><SectionTitle title="Synchronizace" /><View style={[styles.syncCard, { backgroundColor: `${colors.success}15`, borderColor: `${colors.success}55` }]}><MaterialIcons name="cloud-done" size={25} color={colors.success} /><View style={styles.syncCopy}><Text style={[styles.syncTitle, { color: colors.foreground }]}>Cloudové studio je propojeno</Text><Text style={[styles.syncText, { color: colors.muted }]}>Obsah se načítá z tvého zabezpečeného prostoru. Soubory zůstávají oddělené od katalogu.</Text></View></View><View style={styles.statRow}><Stat value={snapshot.data?.albums.length ?? 0} label="alb" /><Stat value={snapshot.data?.documents.length ?? 0} label="textů" /><Stat value={versions} label="MP3 verzí" /></View><SectionTitle title="Kompletní záloha" /><Pressable onPress={() => void exportLibrary()} style={({ pressed }) => [styles.libraryExport, { backgroundColor: colors.primary, opacity: exportWholeLibrary.isPending || pressed ? 0.68 : 1 }]} disabled={exportWholeLibrary.isPending}><MaterialIcons name="archive" size={21} color="#141317" /><View style={styles.libraryExportCopy}><Text style={styles.libraryExportTitle}>{exportWholeLibrary.isPending ? "Připravuji kompletní archiv…" : "Exportovat celou knihovnu"}</Text><Text style={styles.libraryExportText}>Texty, prompty, alba, obrázky, MP3 i metadata v jednom ZIP souboru.</Text></View></Pressable><SectionTitle title="Jak systém pracuje" /><Info icon="edit-note" title="Koncept → skladba" text="Označením textu jako hotového zůstane koncept zachován a vznikne samostatná katalogová položka." /><Info icon="content-copy" title="Bezpečná práce s MP3" text="Při exportu ID3 tagů vzniká nová kopie. Původně nahraná verze se nikdy nepřepisuje." /><Info icon="storage" title="Rozdělené uložení" text="Texty a vazby alb jsou v databázi; přebaly a MP3 jsou v souborovém úložišti." /><Pressable onPress={showLogout} style={({ pressed }) => [styles.logout, { borderColor: colors.border, opacity: pressed ? 0.65 : 1 }]}><MaterialIcons name="logout" size={20} color={colors.error} /><Text style={[styles.logoutText, { color: colors.error }]}>Odhlásit se</Text></Pressable></ScrollView></ScreenContainer>;
}
function Stat({ value, label }: { value: number; label: string }) { const colors = useColors(); return <View style={[styles.stat, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.statValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.statLabel, { color: colors.muted }]}>{label}</Text></View>; }
function Info({ icon, title, text }: { icon: React.ComponentProps<typeof MaterialIcons>["name"]; title: string; text: string }) { const colors = useColors(); return <View style={styles.info}><View style={[styles.infoIcon, { backgroundColor: `${colors.primary}1C` }]}><MaterialIcons name={icon} size={20} color={colors.primary} /></View><View style={styles.infoCopy}><Text style={[styles.infoTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.infoText, { color: colors.muted }]}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ content: { paddingTop: 14, paddingBottom: 33 }, profile: { borderWidth: 1, borderRadius: 20, padding: 15, flexDirection: "row", alignItems: "center", gap: 12 }, avatar: { width: 45, height: 45, borderRadius: 15, alignItems: "center", justifyContent: "center" }, avatarText: { fontSize: 19, fontWeight: "900" }, profileCopy: { flex: 1, gap: 3 }, profileName: { fontSize: 15, fontWeight: "800" }, profileMail: { fontSize: 12 }, syncCard: { borderWidth: 1, padding: 15, borderRadius: 19, flexDirection: "row", gap: 11 }, syncCopy: { flex: 1, gap: 3 }, syncTitle: { fontSize: 14, fontWeight: "800" }, syncText: { fontSize: 12, lineHeight: 17 }, statRow: { flexDirection: "row", gap: 9, marginTop: 10 }, stat: { flex: 1, minHeight: 68, borderWidth: 1, borderRadius: 17, padding: 10, justifyContent: "center" }, statValue: { fontSize: 20, fontWeight: "900" }, statLabel: { fontSize: 11, fontWeight: "700" }, libraryExport: { minHeight: 76, borderRadius: 18, padding: 14, flexDirection: "row", alignItems: "center", gap: 11 }, libraryExportCopy: { flex: 1, gap: 3 }, libraryExportTitle: { color: "#141317", fontSize: 14, fontWeight: "900" }, libraryExportText: { color: "#141317", fontSize: 11, lineHeight: 15 }, info: { flexDirection: "row", gap: 11, marginBottom: 16 }, infoIcon: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, infoCopy: { flex: 1, gap: 3 }, infoTitle: { fontSize: 14, fontWeight: "800" }, infoText: { fontSize: 12, lineHeight: 17 }, logout: { marginTop: 15, height: 50, borderRadius: 15, borderWidth: 1, flexDirection: "row", gap: 8, alignItems: "center", justifyContent: "center" }, logoutText: { fontSize: 14, fontWeight: "800" }, login: { minHeight: 48, borderRadius: 14, alignItems: "center", justifyContent: "center" }, loginText: { color: "#141317", fontWeight: "800" } });
